### ISSUE TITLE
Виден BOT_TOKEN в config_data/config.py

### ISSUE THREAD

**Issue by cl7paBka** [Stremilov/order_119_bot#11]
Лучше бы спрятать токен в .venv и доставать его при помощи:
```python
import os


BOT_TOKEN = os.getenv("BOT_TOKEN")
```
![изображение](https://github.com/user-attachments/assets/366bffd2-a3e6-49dc-a95b-6a307881daca)

**Comment by Stremilov** [comment]
да похуй, я просто приватный реп сделаю
